# Generated by Django 3.0.3 on 2020-03-21 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0003_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cal',
        ),
    ]
