# Generated by Django 3.0.3 on 2020-03-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0006_rec_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rec_img',
            name='img',
            field=models.ImageField(upload_to='new_img'),
        ),
    ]
