# Generated by Django 3.0.3 on 2020-03-24 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0007_auto_20200324_1911'),
    ]

    operations = [
        migrations.DeleteModel(
            name='REC_IMG',
        ),
    ]
