# Generated by Django 3.0.3 on 2020-04-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0008_delete_rec_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='EMOTION',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('emotion_score', models.FloatField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FACE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('face_score', models.FloatField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='IMG',
        ),
    ]
