# Generated by Django 3.0.3 on 2020-04-23 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0011_auto_20200423_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='admin',
        ),
    ]
