# Generated by Django 3.0.3 on 2020-04-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0013_auto_20200428_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warning',
            name='score',
            field=models.FloatField(default='1.0'),
        ),
    ]
