# Generated by Django 3.0.3 on 2020-04-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0014_auto_20200428_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='WARNING_PIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_name', models.CharField(max_length=20)),
                ('acc', models.FloatField(default='0.01')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='model_acc',
            field=models.FloatField(default='0.01'),
        ),
        migrations.AddField(
            model_name='user',
            name='model_loss',
            field=models.FloatField(default='0.01'),
        ),
    ]
