# Generated by Django 3.0.3 on 2020-05-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0015_auto_20200430_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion',
            name='acc',
            field=models.FloatField(default='0.01'),
        ),
        migrations.AddField(
            model_name='emotion',
            name='pic_name',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warning_pic',
            name='student_number',
            field=models.IntegerField(default='16200001'),
        ),
    ]
