# Generated by Django 3.0.3 on 2020-05-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0016_auto_20200501_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='WARNING_LIST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.IntegerField(default='16200001')),
                ('list', models.CharField(max_length=1000)),
            ],
        ),
    ]
